Repository surfstudio/surf-flutter-app-template, pull requests merged in 2024-02, with the labels that each got.

#73 fix: fixed exception recording in firebase
  lib/runner.dart
Labels: bug

#79 refactor: Organization of the core directory
  lib/common/utils/default_error_handler.dart
  lib/common/utils/disposable_object/disposable_object.dart
  lib/common/utils/disposable_object/i_disposable_object.dart
  lib/common/utils/logger/crashlytics_strategy.dart
  lib/common/utils/logger/log_history.dart
  lib/common/utils/logger/logger.dart
  lib/config/environment/environment.dart
  lib/features/app/di/app_scope.dart
Labels: documentation

#80 chore: deprecated gradle apply method
  README.md
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
Labels: dependency

#71 feat: Added uikit
  assets/icons/photo_placeholder.svg
  lib/assets/colors/color_palette.dart
  lib/assets/colors/color_scheme.dart
  lib/assets/res/svg_icons.dart
  lib/uikit/alerts/app_alert.dart
  lib/uikit/alerts/app_alert_action.dart
  lib/uikit/bottom_sheet/.gitkeep
  lib/uikit/buttons/animated_pressed_scale.dart
  lib/uikit/buttons/scaled_gesture_detector.dart
  lib/uikit/fields/.gitkeep
  lib/uikit/icons/.gitkeep
  lib/uikit/images/image_placeholder_widget.dart
  lib/uikit/loaders/.gitkeep
  lib/uikit/others/conditional_wrapper.dart
  lib/uikit/others/inactive_wrapper.dart
  lib/uikit/others/lost_focus_wrapper.dart
  lib/uikit/others/shimmer.dart
  lib/uikit/snacks/.gitkeep
  pubspec.lock
  pubspec.yaml
  test/svg_icons_test.dart
Labels: enhancement

#72 feat: added golden tests for uikit
  pubspec.lock
  test/features/dash/screen/goldens/dark.dash_screen.iphone11.png
  test/features/dash/screen/goldens/dark.dash_screen.phone.png
  test/features/dash/screen/goldens/dark.dash_screen.pixel 4a.png
  test/features/dash/screen/goldens/light.dash_screen.iphone11.png
  test/features/dash/screen/goldens/light.dash_screen.phone.png
  test/features/dash/screen/goldens/light.dash_screen.pixel 4a.png
  test/uikit/alerts/app_alert_test.dart
  test/uikit/alerts/goldens/app_alert.png
  test/uikit/images/goldens/image_placeholder_widget.png
  test/uikit/images/image_placeholder_widget_test.dart
  test/uikit/others/goldens/incative_wrapper.png
  test/uikit/others/inactive_wrapper_test.dart
Labels: enhancement

#77 refactor: moved common, shared and core folders
  docs/architecture_and_project_structure.md
  lib/common/mixin/theme_mixin.dart
  lib/common/service/log_history/log_history_service.dart
  lib/common/service/log_history/log_history_service_impl.dart
  lib/common/service/theme/theme_service.dart
  lib/common/service/theme/theme_service_impl.dart
  lib/common/utils/analytics/amplitude/amplitude_analytic_tracker.dart
  lib/common/utils/analytics/base/analytic_event.dart
  lib/common/utils/analytics/base/has_id.dart
  lib/common/utils/analytics/base/has_map_params.dart
  lib/common/utils/analytics/event/common/first_run.dart
  lib/common/utils/analytics/event/common/track_analytics_example.dart
  lib/common/utils/analytics/firebase/firebase_analytic_tracker.dart
  lib/common/utils/analytics/ids_analytics_events.dart
  lib/common/utils/analytics/mock/mock_amplitude_analytics.dart
  lib/common/utils/analytics/mock/mock_firebase_analytics.dart
  lib/common/utils/analytics/service/analytics_service.dart
  lib/common/utils/analytics/service/analytics_service_impl.dart
  lib/common/utils/default_error_handler.dart
  lib/common/utils/disposable_object/disposable_object.dart
  lib/common/utils/disposable_object/i_disposable_object.dart
  lib/common/utils/logger/crashlytics_strategy.dart
  lib/common/utils/logger/log_history.dart
  lib/common/utils/logger/logger.dart
  lib/common/widgets/di_scope/di_scope.dart
  lib/config/environment/environment.dart
  lib/core/.gitkeep
  lib/features/app/app.dart
  lib/features/app/di/app_scope.dart
  lib/features/common/utils/analytics/base/analytic_event.dart
  lib/features/dash/screen/dash_screen_wm.dart
  lib/features/debug/screens/debug_screen/debug_screen_model.dart
  lib/features/debug/screens/log_history_screen/log_history_model.dart
  lib/features/info/screen/info_screen_wm.dart
  lib/features/shared/data/mappers/.gitkeep
  lib/features/shared/data/repositories/.gitkeep
  lib/features/shared/di/.gitkeep
  lib/features/shared/domain/entities/.gitkeep
  lib/features/shared/domain/repositories/.gitkeep
  lib/features/shared/presentation/screens/.gitkeep
  lib/features/shared/presentation/widgets/.gitkeep
  lib/features/temp/screens/temp_screen/temp_screen_model.dart
  lib/features/temp/screens/temp_screen/temp_screen_widget_model.dart
  test/features/debug/screens/debug_screen/debug_screen_model_test.dart
  test/mocks/base_widget_test_wrapper.dart
Labels: documentation

#78 feat: Added diagram of the recommended architecture to the documentation
  docs/architecture_and_project_structure.md
  docs/images/architecture.png
Labels: enhancement

#84 feat: Added converter class
  lib/core/architecture/data/converter/converter.dart
Labels: enhancement

#74 feat: Updated analytics version
  docs/analytic.md
  lib/common/utils/analytics/amplitude/amplitude_analytic_tracker.dart
  lib/common/utils/analytics/firebase/firebase_analytic_strategy.dart
  lib/common/utils/analytics/firebase/firebase_analytic_tracker.dart
  lib/common/utils/analytics/mock/mock_amplitude_analytics.dart
  lib/common/utils/analytics/service/analytics_service.dart
  lib/common/utils/analytics/service/analytics_service_impl.dart
  lib/features/app/di/app_scope.dart
  lib/features/dash/presentation/dash_wm.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#83 feat: added Result class, RequestOperation typedef and docs for them
  docs/architecture_and_project_structure.md
  lib/core/architecture/data/converter/converter.dart
  lib/core/architecture/domain/entity/failure.dart
  lib/core/architecture/domain/entity/request_operation.dart
  lib/core/architecture/domain/entity/result.dart
Labels: enhancement

#88 fix: added files generated by the spider script
  analysis_options.yaml
  lib/assets/images.dart
  lib/assets/resources.dart
  lib/assets/svg_icons.dart
Labels: bug

#75 feat: Updated logger version
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/common/service/log_history/log_history_service.dart
  lib/common/service/log_history/log_history_service_impl.dart
  lib/common/utils/logger/crashlytics_log_strategy.dart
  lib/common/utils/logger/crashlytics_strategy.dart
  lib/common/utils/logger/debug_log_strategy.dart
  lib/common/utils/logger/log_history.dart
  lib/common/utils/logger/logger.dart
  lib/config/environment/environment.dart
  lib/features/app/app.dart
  lib/features/app/di/app_scope.dart
  lib/features/debug/presentation/screens/debug/debug_screen.dart
  lib/features/debug/presentation/screens/debug/debug_wm.dart
  lib/features/debug/presentation/screens/log_history/log_history_model.dart
  lib/features/debug/presentation/screens/log_history/log_history_screen.dart
  lib/features/debug/presentation/screens/log_history/log_history_wm.dart
  lib/features/navigation/service/router.dart
  lib/features/navigation/service/router.gr.dart
  lib/features/temp/presentation/screens/temp/temp_wm.dart
  lib/runner.dart
  lib/uikit/others/conditional_wrapper.dart
  pubspec.lock
  pubspec.yaml
  test/images_test.dart
  test/svg_icons_test.dart
Labels: dependency

#90 feat: add Flutter.podspec to gitignore
  ios/.gitignore
Labels: enhancement

#91 feat: rearrange folders
  lib/common/mixin/localization_mixin.dart
  lib/common/widgets/conditional_wrapper.dart
  lib/common/widgets/di_scope.dart
  lib/common/widgets/lost_focus_wrapper.dart
  lib/features/app/app.dart
  lib/features/common/utils/mixin/theme_mixin.dart
  lib/features/dash/presentation/dash_flow.dart
  lib/features/dash/presentation/dash_wm.dart
  lib/features/debug/presentation/debug_flow.dart
  lib/features/info/presentation/info_flow.dart
  lib/features/info/presentation/screens/info/info_wm.dart
  lib/features/temp/presentation/screens/temp/temp_wm.dart
  lib/features/temp/presentation/temp_flow.dart
  lib/uikit/buttons/scaled_gesture_detector.dart
  lib/uikit/others/shimmer.dart
Labels: enhancement
